# Generated by Django 3.0.5 on 2020-04-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubleHaoapp', '0009_student_stype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('consume', models.TextField()),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubleHaoapp.Student', to_field='Sid')),
            ],
        ),
    ]
