# Generated by Django 3.0.5 on 2020-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubleHaoapp', '0010_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='amount',
            field=models.CharField(max_length=15),
        ),
    ]
