# Generated by Django 3.0.5 on 2020-06-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubleHaoapp', '0011_auto_20200427_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kssj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kssjmessage', models.TextField()),
                ('Kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubleHaoapp.Student', to_field='Sid')),
            ],
        ),
    ]
